[FEATURE#35371] ajout du translator sur toutes les routes sur doctrine service provider
etna-alternance/composer-doctrine-service-provider pull request #2
Opened 2016-10-10 08:52 UTC by rinaz-a

Ajout d'un `app->after` qui passe sur toutes les routes pour effectuer la traduction du message de retour si elle existe.

2016-10-10 09:37 UTC, lapwil approved these changes
OK

2016-10-10 09:37 UTC, misseur approved these changes

2016-10-11 12:40 UTC, staciekith commented on src/DoctrineDbProfiler.php
> +                    if (is_string($content)) {
T'es sûr qu'on rentre dans ce if quand c'est un retour des validators sur contractmanager-api ? (quand c'est un array du coup)

2016-10-11 12:44 UTC, staciekith commented on src/DoctrineDbProfiler.php
> +                    if (is_string($content)) {
Est-ce qu'il faudrait pas vérifier en plus si c'est vraiment une erreur qu'on a ?

2016-10-11 13:28 UTC, rinaz-a commented on src/DoctrineDbProfiler.php
> +                    if (is_string($content)) {
ça change rien car si il n'y a pas de traduction c'est le message d'origine qui est renvoyé

2016-10-20 07:48 UTC, Hazainn approved these changes

2016-10-20 08:55 UTC, staciekith requested changes

2016-10-20 08:55 UTC, staciekith commented on src/DoctrineDbProfiler.php
> +                        $translated = json_encode($app["translator"]->trans($content, [], 'abort'));
mmh, le truc avec ça c'est que si une api n'a pas register le translator, ton appel à `$app["translator"]->trans(...)` va te faire une erreur, faudrait vérifier que le translator est bien présent dans ton app du coup :)

2016-10-20 08:55 UTC, staciekith commented on src/DoctrineDbProfiler.php
> +                    if (is_string($content)) {
okay pour ça !

2016-10-26 09:03 UTC, Teegie commented on src/DoctrineDbProfiler.php
> +                        $translated = json_encode($app["translator"]->trans($content, [], 'abort'));
@selim ?

2016-10-26 14:53 UTC, rinaz-a commented on src/DoctrineDbProfiler.php
> +                        $translated = json_encode($app["translator"]->trans($content, [], 'abort'));
je vais close ça en fait car on a changé d'avis ce matin on va le faire autrement

2016-10-26 14:53 UTC, closed without merging